### ISSUE TITLE
[PROJECT] Nexandria explorer

### ISSUE THREAD

**Issue by vikpande** [near/Infrastructure-Working-Group#25]
**Summary**

Identify an alternate explorer to NEARblocks 

**Goals & Milestones**

Find an alternate to NEARblocks that is more stable and performant with some multi-chain feature options in the future. 

**Task List**

- Harshit and Vik to share a list of features required to build the RFP
- Vik to share the size of Data Lake (compressed) , validator and archival nodes. - Done.  
- Review the proposal & share with eco infra committee
```[tasklist]
### Tasks
- [ ] https://github.com/near/Infrastructure-Working-Group/issues/45
- [ ] Work on scope and timelines for implementation
- [ ] https://github.com/near/Infrastructure-Working-Group/issues/46
```

```[tasklist]
### Tasks
```

**Comment by trechriron** [comment]
@vikpande  - what is the status?

**Comment by trechriron** [comment]
Proposal rejected.
